name: AI Code Review (Hugging Face)

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.repository }}

      - name: Get PR diff
        run: |
          # Fetch the base branch (the branch PR is targeting)
          git fetch origin ${{ github.event.pull_request.base.ref }}

          # Fetch the PR head safely using pull request number
          git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-${{ github.event.pull_request.number }}

          # Generate diff between base and PR head
          git diff origin/${{ github.event.pull_request.base.ref }}...pr-${{ github.event.pull_request.number }} > changes.diff

      - name: Run AI Review with HuggingFace
        run: |
          pip install requests jq
          DIFF=$(cat changes.diff | head -c 4000)  # trim to 4000 chars

          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.HF_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"inputs\":\"You are a code reviewer. Review this code diff for bugs, readability, and improvements. Be concise and helpful:\\n$DIFF\"}" \
            https://api-inference.huggingface.co/models/bigcode/starcoder2-3b)

          echo "Raw response: $RESPONSE"

          # Extract AI output safely: handle generated_text OR error OR fallback
          echo "$RESPONSE" | jq -r '
            if type=="array" and .[0].generated_text then .[0].generated_text
            elif .error then "⚠️ Hugging Face Error: " + .error
            else "AI review failed or returned empty response."
            end
          ' > review.txt

      - name: Comment on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: review.txt
